GooglePlayInstant/Android.cs
GooglePlayInstant/Editor/AndroidManifest/AndroidManifestHelper.cs
GooglePlayInstant/InstallLauncher.cs
GooglePlayInstant/Tests/Editor/AndroidManifest/AndroidManifestHelperTests.cs

The ShowInstallPrompt method can be called from the click listener
of an "Install" button to launch a Play Store install dialog.
This is an easier-to-use alternative to the functionality provided by
including the instantapps-1.1.0.aar file in a Unity project and
calling showInstallPrompt:
https://developer.android.com/topic/google-play-instant/reference

Add method to start app installation

---

GooglePlayInstant/Editor/AndroidBuildTools.cs
GooglePlayInstant/Tests/Editor/AndroidBuildToolsTests.cs
build.gradle

Upcoming features need access to the latest Android build-tools.
Add a utility method for finding this file path.
Also bump version to 0.7 for the next release.

Add a utility for finding the latest build-tools

---

GooglePlayInstant/Editor/PostBuildCommandLineDialog.cs

In Unity 5.6 there is no OnGUI() callback after the AppDomain is
reset unless the user interacts with the window, e.g. by clicking
on it. This is the case on both Mac and Windows.
Switch the AppDomain reset check to Update() which is called more
often and works for Unity 5.6.

Switch PostBuildCommandLineDialog to Update()

---

GooglePlayInstant/Editor/ApkSigner.cs
GooglePlayInstant/Editor/BuildSettingsWindow.cs
GooglePlayInstant/Editor/GooglePlayServices/CommandLine.cs
GooglePlayInstant/Editor/PlayInstantBuildConfiguration.cs
GooglePlayInstant/Editor/PlayInstantBuilder.cs
GooglePlayInstant/Editor/PlayInstantPublisher.cs
GooglePlayInstant/Editor/PlayInstantRunner.cs

Update all command line calls to wrap file/directory paths in double quotes
if the path contains at least one space.
Update the Build Settings screen to trim whitespace in text fields when
clicking "Save".
Fixes #19

Handle whitespace

---

GooglePlayInstant/Editor/BuildSettingsWindow.cs
GooglePlayInstant/Editor/PlayInstantEditorMenu.cs
GooglePlayInstant/Editor/QuickDeploy/AssetBundleBuilder.cs
GooglePlayInstant/Editor/QuickDeploy/AssetBundleVerifierWindow.cs
GooglePlayInstant/Editor/QuickDeploy/DialogHelper.cs
GooglePlayInstant/Editor/QuickDeploy/LoadingScreenGenerator.cs
GooglePlayInstant/Editor/QuickDeploy/PlayInstantSceneTreeView.cs
GooglePlayInstant/Editor/QuickDeploy/QuickDeployConfig.cs
GooglePlayInstant/Editor/QuickDeploy/QuickDeployWindow.cs
GooglePlayInstant/LoadingScreen/LoadingBar.cs
GooglePlayInstant/LoadingScreen/LoadingScreenConfig.cs
GooglePlayInstant/LoadingScreen/LoadingScreenScript.cs
GooglePlayInstant/Samples/SphereBlast/scripts/AssetBundleDownloader.cs
GooglePlayInstant/Tests/Editor/QuickDeploy/AssetBundleVerifierTest.cs
GooglePlayInstant/Tests/Editor/QuickDeploy/ConfigurationTest.cs
GooglePlayInstant/Tests/Editor/QuickDeploy/LoadingScreenGeneratorTest.cs

One way to reduce the size of a Unity-based instant app is to place some assets in an AssetBundle and download that AssetBundle from a loading screen at game startup.
Quick Deploy makes it easier to use AssetBundles in this fashion via two main features:
- it simplifies the creation of an AssetBundle from existing scenes
- it provides a loading screen that displays progress in downloading the AssetBundle from a server

Introduce Quick Deploy

---

GooglePlayInstant/Editor/QuickDeploy/AssetBundleBuilder.cs
GooglePlayInstant/Editor/QuickDeploy/LoadingScreenGenerator.cs
GooglePlayInstant/Editor/QuickDeploy/PlayInstantSceneTreeView.cs
GooglePlayInstant/Editor/QuickDeploy/QuickDeployConfig.cs
GooglePlayInstant/Editor/QuickDeploy/QuickDeployWindow.cs

* Refresh AssetDatabase when making AssetBundles so that the user can see them in their hierarchy immediately.
* Save selected scenes to config file.

Quick Deploy - AssetBundle tab

---

GooglePlayInstant/Editor/PlayInstantSettingPolicy.cs

Forthcoming Android App Bundle support will make it possible to
build an app bundle that supports multiple ABIs, but only delivers
a single ABI's libraries to a given device.
We also want to be able to build test apps that work on x86 emulators.

Remove restriction for ARMv7 only

---

GooglePlayInstant/Editor/AppBundlePublisher.cs
GooglePlayInstant/Editor/PlayInstantBuilder.cs
GooglePlayInstant/Editor/PlayInstantEditorMenu.cs
GooglePlayInstant/Editor/PlayInstantPublisher.cs
GooglePlayInstant/Editor/PlayInstantRunner.cs
GooglePlayInstant/Editor/PlayInstantSettingPolicy.cs

Android App Bundles are natively supported as of Unity 2018.3; for
this version provide a menu option to build them. For other types
of builds, e.g. Build & Run, disable app bundle support.
Also change the managed code stripping policy to use the new
setting added in 2018.3.

Add App Bundle support for Unity 2018.3

---

GooglePlayInstant/Samples/TestApp/Scenes/TestScene.unity

This should get rid of cubemap errors while building in headless mode.

Removed environment lighting from TestScene

---

build.gradle

Removed some code that was adapted from other Google Unity gradle files, e.g.
https://github.com/googlesamples/google-signin-unity/blob/master/build.gradle#L47
Specifying the Unity Editor executable path from the command line seems
to work better without that code.

Fix "gradle -PunityExe=/path/to/unity/editor"

---

GooglePlayInstant/Editor/Bundletool.cs
GooglePlayInstant/Editor/BundletoolDownloadWindow.cs
GooglePlayInstant/Editor/WindowUtils.cs

Bundletool is required for creating Android App Bundles on versions of
Unity prior to 2018.3, and for creating sets of APKs from bundles.

Add UI for downloading bundletool

---

GooglePlayInstant/Editor/ApkSigner.cs
GooglePlayInstant/Editor/PlayInstantBuilder.cs

If there is an error running apksigner, display the error in
addition to logging it.
Treat an empty key alias as reason to prefer the debug keystore,
better reflecting how the Unity Editor handles switching the
Key Alias to "Unsigned (debug)".

Apksigner improvements

---

GooglePlayInstant/Editor/AndroidAssetPackagingTool.cs
GooglePlayInstant/Editor/ApkSigner.cs
GooglePlayInstant/Editor/Bundletool.cs
GooglePlayInstant/Editor/GooglePlayServices/CommandLine.cs
GooglePlayInstant/Editor/PlayInstantRunner.cs
GooglePlayInstant/Editor/ZipUtils.cs

Add missing double quotes on aapt2 and bundletool.
Consistently wrap double quotes around paths.

CommandLine.QuotePath() fixes

---

GooglePlayInstant/Editor/QuickDeploy/DialogHelper.cs
GooglePlayInstant/Editor/QuickDeploy/LoadingScreenGenerator.cs
GooglePlayInstant/Editor/QuickDeploy/QuickDeployWindow.cs

`EditorUtility.SaveFilePanel` returns an absolute path but `EditorSceneManager.SaveScene` expects a path relative to the Assets folder.
Added a `DialogHelper.SaveFilePanelInProject` which will return a relative path and show the user an error, prompting them to retry, if they specify a path outside of the Assets folder. This behavior is identical to Unity's `EditorUtility.SaveFilePanelInProject` but it allows us to specify a default path that isn't the Assets folder.

Changed scene paths to be relative to the Asset folder

---

GooglePlayInstant/Editor/QuickDeploy/LoadingScreenGenerator.cs
GooglePlayInstant/Editor/QuickDeploy/PlayInstantSceneTreeView.cs
GooglePlayInstant/Editor/QuickDeploy/QuickDeployConfig.cs
GooglePlayInstant/Editor/QuickDeploy/QuickDeployWindow.cs
GooglePlayInstant/LoadingScreen/LoadingBar.cs
GooglePlayInstant/LoadingScreen/LoadingScreen.cs
GooglePlayInstant/Tests/Editor/QuickDeploy/ConfigurationTest.cs

- Removed all compiler warnings.
- Fixed issue where selecting multiple scenes and hitting right-click -> Remove Selected, would only remove the item that was right-clicked.
- Fixed issue where most textures by default would have their AspectRatioFitters configured incorrectly when they were used a background in the loading scene.
- Added default file paths for when users save an AssetBundle or a loading scene without a config file.
- Updated the QuickDeployWindow so that it saves its config file whenever the user changes a field. Previously the config file was only saved when the user hit "Build AssetBundle" or "Create Loading Screen"

Miscellaneous QuickDeploy Updates

---

GooglePlayInstant/Editor/AndroidAssetPackagingTool.cs
GooglePlayInstant/Editor/AndroidManifest/PostGenerateGradleProjectAndroidManifestUpdater.cs
GooglePlayInstant/Editor/AndroidSdkPackageInstaller.cs
GooglePlayInstant/Editor/AppBundleBuilder.cs
GooglePlayInstant/Editor/AppBundlePublisher.cs
GooglePlayInstant/Editor/BuildSettingsWindow.cs
GooglePlayInstant/Editor/BundletoolDownloadWindow.cs
GooglePlayInstant/Editor/PlayInstantBuilder.cs
GooglePlayInstant/Editor/PlayInstantEditorMenu.cs
GooglePlayInstant/Editor/PlayInstantPublisher.cs
GooglePlayInstant/Editor/PlayInstantRunner.cs
GooglePlayInstant/Editor/PlayerSettingsWindow.cs
GooglePlayInstant/Editor/WindowUtils.cs
GooglePlayInstant/Samples/TestApp/Editor/TestAppBuilder.cs

Call bundletool to build an Android App Bundle on Unity 5.6+.
Update TestAppBuilder to also generate a testapp.aab file.

Add app bundle support for pre-2018.3

---

GooglePlayInstant/Editor/AppBundlePublisher.cs
GooglePlayInstant/Editor/PlayInstantBuilder.cs
GooglePlayInstant/Editor/PlayInstantPublisher.cs
GooglePlayInstant/Editor/PlayInstantRunner.cs

On Android versions prior to Oreo, the instant app icon isn't shown
anywhere, so some Unity apps are being uploaded without one. However,
on Oreo and later devices the icon is used, so display a warning when
performing a publish build without an icon.
Also rearrange some of the build prerequisite checks for easier reuse.
Also display publish build errors prior to showing the "Save" dialog.

Check the project for an icon during publish builds

---

GooglePlayInstant/Editor/BuildSettingsWindow.cs
GooglePlayInstant/Tests/Editor/BuildSettingsWindowTests.cs

This may cause confusion, so prevent saving a URL like:
https://instant.apps/my.package.name
Also add unit tests for all of the various URL checks.
Also save any cleanups done by Uri to the string, e.g. HTTPS->https.
Also remove the check for missing host name since Uri already does this.

Disallow host name "instant.apps" for Instant URL

---

GooglePlayInstant/Editor/AndroidManifest/AndroidManifestHelper.cs
GooglePlayInstant/Editor/AndroidManifest/IAndroidManifestUpdater.cs
GooglePlayInstant/Editor/AndroidManifest/LegacyAndroidManifestUpdater.cs
GooglePlayInstant/Editor/AndroidManifest/PostGenerateGradleProjectAndroidManifestUpdater.cs
GooglePlayInstant/Editor/PlayInstantBuilder.cs
GooglePlayInstant/Tests/Editor/AndroidManifest/AndroidManifestHelperTests.cs

Add a <meta-data> element to the <application> element of the Android
manifest indicating which version of the plugin was used.
This is only included for instant app builds.
Example:
<meta-data android:name="play-instant-unity-plugin.version" android:value="1.0"/>

Include plugin version in manifest of instant builds

---

GooglePlayInstant/Editor/QuickDeploy/DialogHelper.cs
GooglePlayInstant/Tests/Editor/QuickDeploy/DialogHelperTest.cs
GooglePlayInstant/Tests/Editor/QuickDeploy/LoadingScreenGeneratorTest.cs

The issue blocked users from selecting a path for the generated loading scene. Instead, it would mistakenly declare that the chosen path was outside the Assets folder, and throw an error.

Fixed save dialog issue on Windows

---

GooglePlayInstant/Editor/GooglePlayServices/CommandLine.cs
GooglePlayInstant/Editor/ZipUtils.cs

Jar was failing to zip files because of quotes around the -C argument. To fix it, we unquote that particular argument and throw an error if the path contains spaces.

Fixed issue with building for play console on windows

---

build.gradle

The exportPlugin task was generating a Unity package with Assets/ as its root folder instead of GooglePlayInstant/

Fixed Unity package export issue

---

GooglePlayInstant/Editor/BuildSettingsWindow.cs
GooglePlayInstant/Editor/PlayerSettingsWindow.cs
GooglePlayInstant/Editor/PluginUpdateWindow.cs

Clean up 3 Unity warnings on unused fields.
Also set minimum window size on 2 windows.

Fix warnings and window sizes

---

build.gradle

IntelliJ-core jar is missing and google depot needs to be added.

Fix Unity 2018 Gradle build

---

GooglePlayInstant/Editor/QuickDeploy/DialogHelper.cs
GooglePlayInstant/Tests/Editor/QuickDeploy/DialogHelperTest.cs

The AbsoluteToRelativePath function was returning paths with a mix of back and forward slashes, instead of paths with just forward slashes.

Fixed failing test on windows

---

GooglePlayInstant/Editor/ApkSigner.cs
GooglePlayInstant/Editor/AppBundlePublisher.cs
GooglePlayInstant/Editor/GooglePlayServices/CommandLine.cs

Signing App Bundles with .NET 4.5 was failing due to inclusion of
a byte order marker (BOM) prefix to the keystore password. Change the
output encoding to explicitly not include a BOM.
Remove line indicating when processes are started; it was there
originally for debugging an issue that no longer occurs.
Fix logging of a message when App Bundle building is complete.

Fix ApkSigner usage with .NET 4.5

---

GooglePlayInstant/Editor/PlayInstantSettingPolicy.cs

Handle API Compability Level differences required for .NET 4.x support.
Fixes #127

Update API Compability Level checks

---

GooglePlayInstant/Editor/PlayInstantRunner.cs
GooglePlayInstant/Editor/PostBuildCommandLineDialog.cs

In Unity versions 2018.3 and newer, the AppDomain isn't reset after building, which causes PostBuildCommandLineDialog to wait indefinitely.
Now, PostBuildCommandLineDialog will only wait for the AppDomain reset in versions older than 2018.3.

Fixed issue where Build and Run would hang on Unity versions 2018.3+

---

GooglePlayInstant/Editor/Bundletool.cs
GooglePlayInstant/Editor/BundletoolDownloadWindow.cs
GooglePlayInstant/Samples/TestApp/Editor/TestAppBuilder.cs

Use wget to download the bundletool jar if necessary.
Also update bundletool from 0.6.0 to 0.7.2.

Download bundletool for command line builds

---

GooglePlayInstant/Editor/BuildSettingsWindow.cs
GooglePlayInstant/Tests/Editor/BuildSettingsWindowTests.cs
README.md

The Launch API is preferred over https://instant.app synthetic URLs.

Update guidance on Instant App URLs

---

GooglePlayInstant/Editor/BuildTools/AndroidSdk.cs
GooglePlayInstant/Editor/BuildTools/AndroidSdk.cs.meta
GooglePlayInstant/Editor/CommandLineBuilder.cs

The AndroidSdkRoot Editor Preference must be set on Unity 2019.2 for it to find the Android SDK.

Introduce workaround for Unity 2019.2 automated builds

---

GooglePlayInstant/Editor/AndroidManifest/PostGenerateGradleProjectAndroidManifestUpdater.cs
GooglePlayInstant/Editor/AppBundlePublisher.cs
GooglePlayInstant/Editor/BuildTools.meta
GooglePlayInstant/Editor/CommandLineBuilder.cs
GooglePlayInstant/Editor/GooglePlayServices/JavaUtilities.cs
GooglePlayInstant/GooglePlayInstantUtils.cs

- Use new AndroidExternalToolsSettings API for Java and SDK paths
- Handle new location of base AndroidManifest.xml
- Extend out the number of versions of 2017.4 that we support for 64 bit
- Add missing BuildTools.meta

Add support for 2019.3
